### ISSUE TITLE
Concat Demuxer

### ISSUE THREAD

**Issue by jaitaiwan** [targodan/ffgopeg#3]
Hey,

I'm just wondering if there's a small example of how one can use ffmpeg's concat demuxer with your library? Or if you could point me in the right direction at the very least?

Thanks!

**Comment by targodan** [comment]
Heya,

only had time for quick google right now, I might be able to get a bit more into this on the weekend. No promisses though.

I found a diff about the implementation in ffmpeg: http://ffmpeg.org/pipermail/ffmpeg-cvslog/2012-December/057881.html
This mentiones a struct representing the concat file and then a `concat_read_packet` function. I didn't find the function or the struct in the go code, so I guess right now it isn't possible to use it. It would have to be added to this project.

Since I have never worked with the cocat demuxer before, could you maybe find or write some C-code using it with the original ffmpeg c library? Then I could prpably easily add it to the go code.

**Comment by jaitaiwan** [comment]
This was the only C code example I could find. I'm not a C coder so I couldn't do up an example for you. Let me know if this helps:

http://stackoverflow.com/questions/16282600/how-to-use-libavformat-to-concat-2-video-files-with-same-codec-re-muxing

**Comment by targodan** [comment]
Sorry, about the inactivity. It's the end of the semester for me and thus exam time. I have glimpsed over the code you found and it seems there are no API calls specific to any `*concat*` function. So it may be possible if all other calls and structs used are present in this library.

You could try to go through the c code and try to find the go equivalents using [this tiny web tool](https://targodan.github.io/ffgopeg/). That tool shows you the names of the go functions and structs equivalent to the c functions and structs.

If you bump on anything that is used in that c code but can not be found by the web tool, let me know and I'll look into including it.
